### ISSUE TITLE
Strange build issue.

### ISSUE THREAD

**Issue by mklgstf** [RoliSoft/Host-Scanner#2]
~/Host-Scanner/build# make
Scanning dependencies of target HostScanner
[  1%] Building CXX object CMakeFiles/HostScanner.dir/ServiceRegexMatcher.cpp.o
[  2%] Building CXX object CMakeFiles/HostScanner.dir/EnterpriseLinuxIdentifier.cpp.o
[  3%] Building CXX object CMakeFiles/HostScanner.dir/BannerProcessor.cpp.o
[  4%] Building CXX object CMakeFiles/HostScanner.dir/UdpScanner.cpp.o
[  6%] Building CXX object CMakeFiles/HostScanner.dir/InternalScanner.cpp.o
[  7%] Building CXX object CMakeFiles/HostScanner.dir/UbuntuLookup.cpp.o
[  8%] Building CXX object CMakeFiles/HostScanner.dir/FedoraIdentifier.cpp.o
[  9%] Building CXX object CMakeFiles/HostScanner.dir/TcpScanner.cpp.o
[ 10%] Building CXX object CMakeFiles/HostScanner.dir/HostScannerFactory.cpp.o
[ 12%] Building CXX object CMakeFiles/HostScanner.dir/VendorPackageLookup.cpp.o
[ 13%] Building CXX object CMakeFiles/HostScanner.dir/EnterpriseLinuxLookup.cpp.o
[ 14%] Building CXX object CMakeFiles/HostScanner.dir/ArpPinger.cpp.o
[ 15%] Building CXX object CMakeFiles/HostScanner.dir/NmapScanner.cpp.o
[ 17%] Building CXX object CMakeFiles/HostScanner.dir/Utils.cpp.o
[ 18%] Building CXX object CMakeFiles/HostScanner.dir/LooquerScanner.cpp.o
[ 19%] Building CXX object CMakeFiles/HostScanner.dir/TaskQueueRunner.cpp.o
[ 20%] Building CXX object CMakeFiles/HostScanner.dir/WindowsIdentifier.cpp.o
[ 21%] Building CXX object CMakeFiles/HostScanner.dir/Host.cpp.o
[ 23%] Building CXX object CMakeFiles/HostScanner.dir/UbuntuIdentifier.cpp.o
[ 24%] Building CXX object CMakeFiles/HostScanner.dir/ServiceScanner.cpp.o
[ 25%] Building CXX object CMakeFiles/HostScanner.dir/DebianLookup.cpp.o
[ 26%] Building CXX object CMakeFiles/HostScanner.dir/ProtocolTokenizer.cpp.o
[ 28%] Building CXX object CMakeFiles/HostScanner.dir/ThreeDigitTokenizer.cpp.o
[ 29%] Building CXX object CMakeFiles/HostScanner.dir/CpeDictionaryMatcher.cpp.o
[ 30%] Building CXX object CMakeFiles/HostScanner.dir/HttpTokenizer.cpp.o
[ 31%] Building CXX object CMakeFiles/HostScanner.dir/Format.cpp.o
[ 32%] Building CXX object CMakeFiles/HostScanner.dir/OperatingSystemIdentifier.cpp.o
[ 34%] Building CXX object CMakeFiles/HostScanner.dir/CensysScanner.cpp.o
[ 35%] Building CXX object CMakeFiles/HostScanner.dir/ConcurrentQueue.cpp.o
[ 36%] Building CXX object CMakeFiles/HostScanner.dir/Service.cpp.o
[ 37%] Building CXX object CMakeFiles/HostScanner.dir/DataReader.cpp.o
[ 39%] Building CXX object CMakeFiles/HostScanner.dir/IcmpPinger.cpp.o
[ 40%] Building CXX object CMakeFiles/HostScanner.dir/HostScanner.cpp.o
[ 41%] Building CXX object CMakeFiles/HostScanner.dir/VulnerabilityLookup.cpp.o
[ 42%] Building CXX object CMakeFiles/HostScanner.dir/VendorLookupFactory.cpp.o
[ 43%] Building CXX object CMakeFiles/HostScanner.dir/PassiveScanner.cpp.o
[ 45%] Building CXX object CMakeFiles/HostScanner.dir/DebianIdentifier.cpp.o
[ 46%] Building CXX object CMakeFiles/HostScanner.dir/ShodanScanner.cpp.o
[ 47%] Building CXX object CMakeFiles/HostScanner.dir/ServiceScannerFactory.cpp.o
[ 48%] Building CXX object CMakeFiles/HostScanner.dir/Main.cpp.o
[ 50%] Linking CXX executable HostScanner
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so: undefined reference to symbol 'inflateInit2_'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/HostScanner.dir/build.make:1117: recipe for target 'HostScanner' failed
make[2]: **\* [HostScanner] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/HostScanner.dir/all' failed
make[1]: **\* [CMakeFiles/HostScanner.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

Ubuntu 16.04 x64. 
What could be the problem?

**Comment by RoliSoft** [comment]
During development I had a few issues related to how I link with zlib. Some distributions package Boost's iostreams library with zlib support, while others don't.

Debian and Kali package it with zlib, but I'm not sure about Ubuntu, however they most likely also do.

Try modifying the CMakeFiles.txt and add:

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lz")

Even though you shouldn't be doing this, I found with earlier versions of gcc it seems to fix the issue.

Alternatively, you can try recompiling boost with zlib support.

Oooor, just run `cmake -DWITHOUT_ZLIB=1`. The only thing you won't be able to do is to load compressed data files directly, so make sure to run `gzip -d *.gz` in the data folder.

**Comment by mklgstf** [comment]
Thank you for the explanation.
